### ISSUE TITLE
薬情報登録の改善

### ISSUE THREAD

**Issue by ASO1701001** [ASO1701001/medice-note#42]
薬情報登録の画像ファイルの登録項目が文字数が長い場合、下に表示されるため、表示できる文字数を超える場合は非表示にする
```css
.file {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
